### ISSUE TITLE
请问生成jwt的时候 Username是做什么用的

### ISSUE THREAD

**Issue by Jetereting** [juusechec/jwt-beego#4]
请问生成jwt的时候 Username是做什么用的，我想要在验证jwt 的时候取出Username可以吗？

**Comment by juusechec** [comment]
I've use package "github.com/dgrijalva/jwt-go", you can omit some params of "https://github.com/dgrijalva/jwt-go/blob/master/claims.go#L18" for this you can delete line "https://github.com/juusechec/jwt-beego/blob/master/jwt.go#L61".
I've put the value "Username" because is in the standard "https://tools.ietf.org/html/rfc7519#page-9" and would be important to web services in case of needed to write logs.

**Comment by Jetereting** [comment]
Thank you!
